-- MySQL Script generated by MySQL Workbench
-- Mon Dec 28 22:07:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`album` (
  `idalbum` INT NOT NULL COMMENT '\n	',
  `cromosDesbloqueados` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `cromosTotales` INT NULL,
  PRIMARY KEY (`idalbum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`baul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`baul` (
  `idbaul` INT NOT NULL,
  `cantidadRepeticiones` INT NOT NULL,
  PRIMARY KEY (`idbaul`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tematica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tematica` (
  `idtematica` INT NOT NULL,
  `nombreTematica` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  `tematicacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idtematica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cromo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cromo` (
  `idcromo` INT NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `img` BLOB NOT NULL,
  `numero` INT NOT NULL,
  `tematica_idtematica` INT NOT NULL,
  PRIMARY KEY (`idcromo`, `tematica_idtematica`),
  INDEX `fk_cromo_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_cromo_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematica` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pregunta` (
  `idpregunta` INT NOT NULL,
  `pregunta` VARCHAR(200) NOT NULL,
  `respuesta_idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idpregunta`, `respuesta_idrespuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`respuesta` (
  `idrespuesta` INT NOT NULL,
  `respuesta` VARCHAR(150) NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  `pregunta_respuesta_idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`, `pregunta_idpregunta`, `pregunta_respuesta_idrespuesta`),
  INDEX `fk_respuesta_pregunta1_idx` (`pregunta_idpregunta` ASC, `pregunta_respuesta_idrespuesta` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta` , `pregunta_respuesta_idrespuesta`)
    REFERENCES `mydb`.`pregunta` (`idpregunta` , `respuesta_idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `nickname` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `pais` VARCHAR(40) NOT NULL,
  `edad` INT NOT NULL,
  `contraseña` VARCHAR(150) NOT NULL,
  `album_idalbum` INT NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `album_idalbum`, `rol`),
  INDEX `fk_usuario_album_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_usuario_Rol1_idx` (`rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_album`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_Rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tematica_has_album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tematica_has_album` (
  `tematica_idtematica` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  PRIMARY KEY (`tematica_idtematica`, `album_idalbum`),
  INDEX `fk_tematica_has_album_album1_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_tematica_has_album_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_tematica_has_album_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematica` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tematica_has_album_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad` (
  `idactividad` INT NOT NULL,
  `nombreActividad` VARCHAR(45) NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  `pregunta_respuesta_idrespuesta` INT NOT NULL,
  `tematica_idtematica` INT NOT NULL,
  PRIMARY KEY (`idactividad`, `pregunta_idpregunta`, `pregunta_respuesta_idrespuesta`, `tematica_idtematica`),
  INDEX `fk_actividad_pregunta1_idx` (`pregunta_idpregunta` ASC, `pregunta_respuesta_idrespuesta` ASC) VISIBLE,
  INDEX `fk_actividad_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_actividad_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta` , `pregunta_respuesta_idrespuesta`)
    REFERENCES `mydb`.`pregunta` (`idpregunta` , `respuesta_idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematica` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cromo_has_baul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cromo_has_baul` (
  `cromo_idcromo` INT NOT NULL,
  `cromo_tematica_idtematica` INT NOT NULL,
  `baul_idbaul` INT NOT NULL,
  PRIMARY KEY (`cromo_idcromo`, `cromo_tematica_idtematica`, `baul_idbaul`),
  INDEX `fk_cromo_has_baul_baul1_idx` (`baul_idbaul` ASC) VISIBLE,
  INDEX `fk_cromo_has_baul_cromo1_idx` (`cromo_idcromo` ASC, `cromo_tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_cromo_has_baul_cromo1`
    FOREIGN KEY (`cromo_idcromo` , `cromo_tematica_idtematica`)
    REFERENCES `mydb`.`cromo` (`idcromo` , `tematica_idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cromo_has_baul_baul1`
    FOREIGN KEY (`baul_idbaul`)
    REFERENCES `mydb`.`baul` (`idbaul`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
