-- MySQL Script generated by MySQL Workbench
-- Mon Jan  4 21:19:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`albums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`albums` ;

CREATE TABLE IF NOT EXISTS `mydb`.`albums` (
  `idalbum` INT NOT NULL COMMENT '\n	',
  `cromosDesbloqueados` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `nombre` VARCHAR(50) NULL,
  `albumcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idalbum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tematicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tematicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tematicas` (
  `idtematica` INT NOT NULL,
  `nombreTematica` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idtematica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cromos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cromos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cromos` (
  `idcromo` INT NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  `imgURL` VARCHAR(150) NOT NULL,
  `numero` INT NOT NULL,
  `tematica_idtematica` INT NOT NULL,
  PRIMARY KEY (`idcromo`, `tematica_idtematica`),
  INDEX `fk_cromo_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_cromo_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematicas` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`desbloqueados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`desbloqueados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`desbloqueados` (
  `album_idalbum` INT NOT NULL,
  `cromo_idcromo` INT NOT NULL,
  `cromo_tematica_idtematica` INT NOT NULL,
  `fechaDesbloqueo` VARCHAR(10) NULL,
  PRIMARY KEY (`album_idalbum`, `cromo_idcromo`, `cromo_tematica_idtematica`),
  INDEX `fk_album_has_cromo_cromo1_idx` (`cromo_idcromo` ASC, `cromo_tematica_idtematica` ASC) VISIBLE,
  INDEX `fk_album_has_cromo_album1_idx` (`album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_album_has_cromo_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_has_cromo_cromo1`
    FOREIGN KEY (`cromo_idcromo` , `cromo_tematica_idtematica`)
    REFERENCES `mydb`.`cromos` (`idcromo` , `tematica_idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `idRol` INT NOT NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `nickname` VARCHAR(15) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `pais` VARCHAR(40) NOT NULL,
  `edad` INT NOT NULL,
  `contraseña` VARCHAR(150) NOT NULL,
  `album_idalbum` INT NOT NULL,
  `rol` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `album_idalbum`, `rol`),
  INDEX `fk_usuario_album_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_usuario_Rol1_idx` (`rol` ASC) VISIBLE,
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_album`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_Rol1`
    FOREIGN KEY (`rol`)
    REFERENCES `mydb`.`roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`baules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`baules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`baules` (
  `idbaul` INT NOT NULL,
  `cantidadRepeticiones` INT NOT NULL,
  `desbloqueados_album_idalbum` INT NOT NULL,
  `desbloqueados_cromo_idcromo` INT NOT NULL,
  `desbloqueados_cromo_tematica_idtematica` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idbaul`, `desbloqueados_album_idalbum`, `desbloqueados_cromo_idcromo`, `desbloqueados_cromo_tematica_idtematica`, `usuarios_idusuario`),
  INDEX `fk_baules_desbloqueados1_idx` (`desbloqueados_album_idalbum` ASC, `desbloqueados_cromo_idcromo` ASC, `desbloqueados_cromo_tematica_idtematica` ASC) VISIBLE,
  INDEX `fk_baules_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_baules_desbloqueados1`
    FOREIGN KEY (`desbloqueados_album_idalbum` , `desbloqueados_cromo_idcromo` , `desbloqueados_cromo_tematica_idtematica`)
    REFERENCES `mydb`.`desbloqueados` (`album_idalbum` , `cromo_idcromo` , `cromo_tematica_idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_baules_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `mydb`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`preguntas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`preguntas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`preguntas` (
  `idpregunta` INT NOT NULL,
  `pregunta` VARCHAR(200) NOT NULL,
  `respuesta_idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idpregunta`, `respuesta_idrespuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`respuestas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`respuestas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`respuestas` (
  `idrespuesta` INT NOT NULL,
  `respuesta` VARCHAR(150) NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  `pregunta_respuesta_idrespuesta` INT NOT NULL,
  PRIMARY KEY (`idrespuesta`, `pregunta_idpregunta`, `pregunta_respuesta_idrespuesta`),
  INDEX `fk_respuesta_pregunta1_idx` (`pregunta_idpregunta` ASC, `pregunta_respuesta_idrespuesta` ASC) VISIBLE,
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta` , `pregunta_respuesta_idrespuesta`)
    REFERENCES `mydb`.`preguntas` (`idpregunta` , `respuesta_idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`albums_has_tematicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`albums_has_tematicas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`albums_has_tematicas` (
  `tematica_idtematica` INT NOT NULL,
  `album_idalbum` INT NOT NULL,
  PRIMARY KEY (`tematica_idtematica`, `album_idalbum`),
  INDEX `fk_tematica_has_album_album1_idx` (`album_idalbum` ASC) VISIBLE,
  INDEX `fk_tematica_has_album_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_tematica_has_album_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematicas` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tematica_has_album_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `mydb`.`albums` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`actividades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`actividades` (
  `idactividad` INT NOT NULL,
  `nombreActividad` VARCHAR(45) NOT NULL,
  `pregunta_idpregunta` INT NOT NULL,
  `pregunta_respuesta_idrespuesta` INT NOT NULL,
  `tematica_idtematica` INT NOT NULL,
  PRIMARY KEY (`idactividad`, `pregunta_idpregunta`, `pregunta_respuesta_idrespuesta`, `tematica_idtematica`),
  INDEX `fk_actividad_pregunta1_idx` (`pregunta_idpregunta` ASC, `pregunta_respuesta_idrespuesta` ASC) VISIBLE,
  INDEX `fk_actividad_tematica1_idx` (`tematica_idtematica` ASC) VISIBLE,
  CONSTRAINT `fk_actividad_pregunta1`
    FOREIGN KEY (`pregunta_idpregunta` , `pregunta_respuesta_idrespuesta`)
    REFERENCES `mydb`.`preguntas` (`idpregunta` , `respuesta_idrespuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_tematica1`
    FOREIGN KEY (`tematica_idtematica`)
    REFERENCES `mydb`.`tematicas` (`idtematica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
